# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

env:
  - SPATIALITE_LIBRARY_PATH=""

before_install:
  - pip install --quiet coveralls
  - pip install codecov

install:
  - pip install -r requirements/test.txt

before_script:
  - cd upvcarshare

script:
  - coverage run manage.py test --settings config.settings.test

after_success:
  - coveralls
