# Docker-compose file to launch services during the development.
version: '2'

volumes:
  db-data:
    driver: local

services:

  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile-dev
    container_name: upvcarshare-app
    command: /start-dev.sh
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8888:8888"

  db:
    build: compose/postgis/.
    image: upvcarshare/postgis
    container_name: upvcarshare-db
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: potato
      POSTGRES_DB: upvcarshare
