# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-24 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journeys', '0014_auto_20170530_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('time_window', models.PositiveIntegerField(blank=True, default=30, help_text='Se buscarán por los viajes que salgan hasta con estos minutos de antelación', verbose_name='ventana de tiempo')),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, null=True, verbose_name='¿Vas a realizar este viaje más de una vez?')),
                ('kind', models.PositiveIntegerField(choices=[(0, 'ida'), (1, 'vuelta')], verbose_name='tipo de viaje')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='journeys.Campus', verbose_name='campus')),
                ('driver', models.ForeignKey(blank=True, help_text='user who drives during the journey', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='journeys.Residence', verbose_name='lugar')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='journeys.Transport', verbose_name='Medio de transporte utilizado')),
                ('user', models.ForeignKey(help_text='user who creates the journey', on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.RemoveField(
            model_name='journey',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='time_window',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='user',
        ),
        migrations.AddField(
            model_name='journey',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='journeys.JourneyTemplate'),
        ),
    ]
