# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0015_auto_20170624_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeytemplate',
            name='recurrence',
            field=models.TextField(blank=True, null=True, verbose_name='¿Vas a realizar este viaje más de una vez?'),
        ),
    ]
