# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0016_auto_20170624_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeytemplate',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cuándo creo que voy a llegar*'),
        ),
        migrations.AddField(
            model_name='journeytemplate',
            name='departure',
            field=models.DateTimeField(null=True, verbose_name='Cuándo voy a realizar el viaje*'),
        ),
    ]
