# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-25 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0017_auto_20170624_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='address',
            field=models.TextField(blank=True, default='', help_text='La dirección del lugar, según quieras que la vean los demás.', verbose_name='dirección'),
        ),
    ]
